match_log_directory: '%{pwd}/../log/match_logs'
exhibition_constants: '%{pwd}/../app/constants/exhibition.json'
table_manager_constants: '%{pwd}/../app/constants/table_manager.json'
log_directory: '%{pwd}/../log'
mongoid_config: '%{pwd}/mongoid.yml'
mongoid_env: development
redis_config_file: '%{pwd}/redis.yml'
# error_report:
#   sender: sender@gmail.com
#   recipients: 
#     - recipient@gmail.com
#   smtp:
#     :address: 'smtp.gmail.com'
#     :port: 587
#     :domain: 'gmail.com'
#     :authentication: :plain,
#     :user_name: 'sender@gmail.com'
#     :password: '********'
#     :enable_starttls_auto: true
